name: Flutter CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'  # Use a stable version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test